### ISSUE TITLE
unapproved posts from puppet showing in sidebox

### ISSUE THREAD

**Issue by damian5000** [WildcardSearch/Puppet-Master#3]
Not sure this is a sidebox latest threads issue or puppet master issue. When posting as unapproved with a registered member who is not otherwise moderated, the post registers in sidebox and bumps post to the top. The post not actually viewable by guests/regular members when clicking on the thread. Post shows in unapproved posts mod area as it should.

**Comment by WildcardSearch** [comment]
This should now be fixed @damian5000. Thanks for the report and sorry for the wait.
